version: "3.9"  # Specify a compatible version of the Docker Compose file format

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=microbit.10botics.com
      - LETSENCRYPT_HOST=microbit.10botics.com
      - TZ=Asia/Hong_Kong


